builder:
  track: dev

labels:
  team: estafette-team
  language: ruby

version:
  semver:
    major: 0
    minor: 0

stages:
  trigger-github-pages-build:
    image: extensions/github-pages:dev
    token: estafette.secret(0lWqybC4fzkQrPUo.w5L2gBS_xcXP_z-xd0d1zaFgINmDw9zahmA0YeYygo4uhaTZaC11p6bKbd1XnzJohmVFMVCLQ1Y=.w5Pytw-NusfC8GSdd1V_xbRVAdLono-E2hgCZfAJuc79Gb3Dl7J61Jafiaw5_55U)
    when:
      status == 'succeeded' &&
      branch == 'master'