builder:
  track: dev

labels:
  team: estafette-team
  language: ruby

version:
  semver:
    major: 0
    minor: 0

stages:
  trigger-github-pages-build:
    image: extensions/github-pages:dev
    when:
      status == 'succeeded' &&
      branch == 'master'