builder:
  track: dev

labels:
  team: estafette-team
  language: ruby

version:
  semver:
    major: 0
    minor: 0

stages:
  validate-github-pages-build:
    image: ruby:2.6-alpine
    commands:
    - bundle exec jekyll build