apiVersion: v1
entries:
  estafette-cloudflare-dns:
  - apiVersion: v1
    appVersion: 1.2.52-add-official-helm-chart
    created: "2019-11-05T10:44:08.60940284Z"
    description: Kubernetes controller to set and update dns records in Cloudflare
      for annotated services and ingresses
    digest: 8ff638f37d633265b4d071c68457542883cd86a2c5a89a3279a2579a11f00447
    name: estafette-cloudflare-dns
    urls:
    - https://helm.estafette.io/estafette-cloudflare-dns-1.2.0-pre-52.tgz
    version: 1.2.0-pre-52
generated: "2019-11-05T10:44:08.608765505Z"
